spring:
  profiles:
    include: SECRET-KEY
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://${database-host}/${database-name}
#    username: ${database-user}
#    password: ${database-password}

# 로컬 테스트용
#    url: jdbc:h2:tcp://localhost/~/test-trashhcan # 메모리 내 데이터베이스 URL
#    driver-class-name: org.h2.Driver # H2 드라이버 클래스
#    username: sa # 기본 사용자 이름
#    password: # 기본 비밀번호는 비워둡니다.
#    h2:
#      console:
#        enabled: true # H2 콘솔을 활성화합니다.
#        path: /h2-console # H2 콘솔의 접근 경로

#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: ${google-client-id}
#            client-secret: ${google-client-secret}
#            redirect-uri: ${google-redirect-uri}
#
#          kakao:
#            client-name: kakao
#            authorization-grant-type: authorization_code
#            redirect-uri: ${kakao-redirect-uri}
#            client-id: ${kakao-client-id}
#            client-secret: ${kakao-client-secret}
#            client-authentication-method: client_secret_post
#
#        provider:
#          kakao:
#            authorization-uri: https://kauth.kakao.com/oauth/authorize
#            user-name-attribute: id
#            token-uri: https://kauth.kakao.com/oauth/token
#            user-info-uri: https://kapi.kakao.com/v2/user/me
#  jwt:
#    secret: ${jwt-secret-key}


#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true
#        dialect: org.hibernate.dialect.MySQLDialect


#  logging.level:
#    org.hibernate.SQL: debug
#    org.springframework.web: DEBUG

  datasource:
    url: jdbc:h2:tcp://localhost/~/test-trashhcan # 메모리 내 데이터베이스 URL
    driver-class-name: org.h2.Driver # H2 드라이버 클래스
    username: sa # 기본 사용자 이름
    password: # 기본 비밀번호는 비워둡니다.
  h2:
    console:
      enabled: true # H2 콘솔을 활성화합니다.
      path: /h2-console # H2 콘솔의 접근 경로
  jpa:
    hibernate:
      ddl-auto: update # Hibernate의 DDL 자동 생성 전략 (update, create, create-drop 등)
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: always # 애플리케이션 시작 시 스크립트 초기화 (기본값: embedded)
